# Generated by Django 5.2.5 on 2025-08-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('contacto_principal', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField(blank=True)),
                ('region', models.IntegerField(help_text='Código de región/provincia (ej. 1 para Buenos Aires, etc.)')),
            ],
        ),
    ]
