# Generated by Django 5.2.5 on 2025-08-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('lt', 'Litros'), ('un', 'Unidades'), ('cj', 'Cajas')], default='un', max_length=20)),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumen', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condiciones_almacenamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('valor_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='maestros.tercero')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
